## Neural Network 만듬
- (Layer 1) Convolution layer = (in_c=3, out_c=6, kernel_size=5, stride=1)
- (Layer 1) MaxPool layer = (kernel_size = 2, stride =2)

- (Layer 2) Convolution layer = (in_c=6, out_c=16, kernel_size = 5, stride =1)
- (Layer 2) MaxPool layer = (kernel_size=2, stride=2)

- (Layer 3) view → (batch_size × [16, 13, 29] → batch_size × [6032])
- (Layer 3) Fully_Connect layer → (input=6032, output = 120)
- (Layer 3) Fully_Connect layer → (input = 120, output = 2)

In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim
from torch.utils.data import DataLoader

import torchvision
import torchvision.transforms as transforms

In [50]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [65]:
trans = transforms.Compose([
    transforms .ToTensor()
])
train_data = torchvision.datasets.ImageFolder(root = '../../../PyTorch/custom_data/train_data', transform = trans)

In [66]:
data_loader = DataLoader(dataset = train_data, batch_size = 8, shuffle = True, num_workers=2)

In [67]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3,6,5),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.layer2 = nn.Sequential(
            nn.Conv2d(6, 16, 5),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.layer3 = nn.Sequential(
            nn.Linear(16*13*29, 120),
            nn.ReLU(),
            nn.Linear(120,2)
        )
    
    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.shape[0], -1)
        out = self.layer3(out)
        return out

In [68]:
#testing
net = CNN().to(device)
test_input = (torch.Tensor(3, 3, 64, 128)).to(device)
test_out = net(test_input)

In [84]:
optimizer = optim.Adam(net.parameters(), lr=0.00001)
loss_func = nn.CrossEntropyLoss().to(device)

In [85]:
total_batch = len(data_loader)

epochs = 7
for epoch in range(epochs):
    avg_cost = 0.0
    for num,data in enumerate(data_loader):
        imgs, labels = data
        imgs = imgs.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        out = net(imgs)
        loss = loss_func(out, labels)
        loss.backward()
        optimizer.step()
        
        avg_cost += loss / total_batch
        
    print('[Epoch: {}] cost = {}'.format(epoch+1, avg_cost))
print('Learning Finished!')

[Epoch: 1] cost = 0.0022200082894414663
[Epoch: 2] cost = 0.0018047476187348366
[Epoch: 3] cost = 0.0015094038099050522
[Epoch: 4] cost = 0.0012693830067291856
[Epoch: 5] cost = 0.0010935859754681587
[Epoch: 6] cost = 0.0008963773725554347
[Epoch: 7] cost = 0.0007974323234520853
Learning Finished!


In [86]:
torch.save(net.state_dict(), "./model/model.pth")

In [87]:
new_net = CNN().to(device)

In [88]:
new_net.load_state_dict(torch.load('./model/model.pth'))

<All keys matched successfully>

In [89]:
print(net.layer1[0])
print(new_net.layer1[0])

print(net.layer1[0].weight[0][0][0])
print(new_net.layer1[0].weight[0][0][0])

net.layer1[0].weight[0] == new_net.layer1[0].weight[0]

Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
tensor([ 0.0881,  0.0388, -0.0234, -0.0934,  0.0823], device='cuda:0',
       grad_fn=<SelectBackward>)
tensor([ 0.0881,  0.0388, -0.0234, -0.0934,  0.0823], device='cuda:0',
       grad_fn=<SelectBackward>)


tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]], device='cuda:0')

In [90]:
trans=torchvision.transforms.Compose([
    transforms.Resize((64,128)),
    transforms.ToTensor()    
])
test_data = torchvision.datasets.ImageFolder(root = '../../../PyTorch/custom_data/test_data', transform = trans)

In [91]:
test_set = DataLoader(dataset = test_data, batch_size = len(test_data))

In [92]:
with torch.no_grad():
    for num, data in enumerate(test_set):
        imgs, label = data
        imgs = imgs.to(device)
        label = label.to(device)
        
        prediction = net(imgs)
        
        correct_prediction = torch.argmax(prediction, 1) == label
        
        accuracy = correct_prediction.float().mean()
        print('Accuracy:', accuracy.item())

Accuracy: 1.0
